steps:
  - id: "terraform plan"
    name: 'alpine/terragrunt'
    args: ['terragrunt', 'run-all', 'plan']
    dir : './src/'
    env:
      - "TF_VAR_project=$PROJECT_ID"

  - id: "terraform apply"
    name: 'alpine/terragrunt'
    args: ['terragrunt', 'run-all', 'apply', '--terragrunt-non-interactive']
    dir : './src/'
    env:
      - "TF_VAR_project=$PROJECT_ID"

  - id: "inspec exec commands"
    name: 'cincproject/auditor'
    args: ["exec", './test', "-t", "gcp://"]
    env:
      - "TF_VAR_project=$PROJECT_ID"

  - id: "get configs"
    name: 'gcr.io/cloud-builders/gcloud'
    args: ['./scripts/main.sh']
    entrypoint: 'bash'
    dir: 'no_lib_test'

  - id: "testing gcp by no_lib"
    name: 'cincproject/auditor'
    args: ["exec", './no_lib_test', '-t' , 'gcp://']

  - id: "testing gcp by command"
    name: 'cincproject/auditor'
    args: ["exec", './shared_logic_sample']

  - id: "terraform destroy"
    name: 'alpine/terragrunt'
    args: ['terragrunt', 'run-all', 'destroy', '--terragrunt-non-interactive']
    dir : './src/'
    env:
      - "TF_VAR_project=$PROJECT_ID"
