steps:
  - id: "inspec exec"
    name: 'cincproject/auditor'
    entrypoint: "/bin/bash"
    args:
      - -c
      - |
        cinc-auditor exec ./test/ -t gcp:// --input-file ./test/attributes/attribute_dev.yaml 2>&1 | tee

  - id: "make logs"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "/bin/sh"
    args: ['./test/no_gcp_lib/scripts/get_project_info.sh']

  - id: "inspec exec commands"
    name: 'cincproject/auditor'
    entrypoint: "/bin/bash"
    args:
      - -c
      - |
        cinc-auditor exec ./test/no_gcp_lib 2>&1 | tee

timeout: 3600s
