steps:
  - id: "inspec exec"
    name: 'cincproject/auditor'
    entrypoint: "/bin/bash"
    args:
      - -ceux
      - |
        cinc-auditor exec ./test/ -t gcp:// --input-file ./test/attributes/attribute_dev.yaml 2>&1 | tee
      
timeout: 3600s
