steps:
  - id: "inspec exec"
    name: 'cincproject/auditor'
    entrypoint: "/bin/bash"
    args:
      - -c
      - |
        cinc-auditor exec ./test/ -t gcp:// --input-file ./test/attributes/attribute_dev.yaml 2>&1 | tee

  - id: "make logs"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "/bin/sh"
    args: ['./test/no_gcp_lib/scripts/get_project_info.sh']

  - id: "inspec exec commands"
    name: 'cincproject/auditor'
    entrypoint: "/bin/bash"
    args:
      - -c
      - |
        cinc-auditor exec ./test/no_gcp_lib 2>&1 | tee

  - id: "secret get info"
    name: "ubuntu"
    entrypoint: "bash"
    args: [ "echo", "$$SECRET"]
    secretEnv: ["SECRET"]


  availableSecrets:
    secretMAnager:
      - versionNAme: project/$PROJECT_ID/secrets/secret-sample/versions/1
        env: "SECRET"

timeout: 3600s
