steps:
  - id: "make logs"
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "/bin/sh"
    args: ['./test/no_gcp_lib/scripts/get_project_info.sh']
       
  - id: "inspec exec commands"
    name: 'cincproject/auditor'
    args: ["exec", './test/no_gcp_lib']

timeout: 3600s
