steps:
  - id: "secret get info"
    name: "ubuntu"
    args: [ "echo", "$SECRET"]
    secretEnv: ["SECRET"]

availableSecrets:  
  secretManager:
    - versionName: projects/ca-kitano-study-sandbox/secrets/secret-sample/versions/1
      env: "SECRET"
timeout: 3600s

