steps:
  - id: 'terraform init'
    name: 'hashicorp/terraform'
    args: ["init"]

  - id: 'terraform worspace select'
    name: 'hashicorp/terraform'
    args: ["workspace", "select", "$PROJECT_ID"]

  - id: 'terraform plan'
    name: 'hashicorp/terraform'
    args: ["plan"]

timeout: 3600s
